name: jaspreet

on:
  push:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - run: 
            echo "build successfull"
